services:
  postgres:
    image: postgres:16-alpine
    container_name: stock_etf_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - stock_etf_data:/var/lib/postgresql/data

volumes:
  stock_etf_data: